version: '2'

services:
  postgresql:
    image: ankane/pgvector
    ports:
      - '5432:5432'
    volumes:
      - ./infrastructure/dev/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=prod,dev,test,chatbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_NONROOT_USER=helpme
      - POSTGRES_NONROOT_PASSWORD=mysecretpassword
    networks:
      - api
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - api
  api:
    container_name: helpme_api
    command: yarn dev
    ports:
      - '80:3000'
    depends_on:
      - postgresql
      - redis
    env_file:
      - ./packages/server/.env.docker
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api
  tomcat-server:
    image: tomcat
    networks:
      - api
  shibboleth-sp:
    container_name: shibboleth-sp
    environment:
      - HOSTNAME=example.com
      - IDP_ENTITY_ID=https://samltest.id/saml/idp
      - IDP_METADATA_URL=https://samltest.id/saml/idp
      - SUPPORT_EMAIL=root@localhost
      - SHIB_METADATA_BACKUP_URL=https://samltest.id/saml/idp
      - SHIB_DOWNLOAD_METADATA=true
    build:
      context: .
      dockerfile: local/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    links:
      - tomcat-server
    networks:
      - api
volumes:
  pg:

networks:
  api:
    driver: bridge
