---
- name: Create /etc/apache2/ssl directory
  file:
    path: /etc/apache2/ssl
    state: directory

- name: check if ssl.key exist
  file:
    path: /etc/apache2/ssl/ssl.key
    state: touch
  check_mode: yes
  register: ssl_key

- name: Generate an OpenSSL private key with the default values
  openssl_privatekey:
    path: "/etc/apache2/ssl/ssl.key"
  # TODO: validate how ssl.key register checks for presence of the file. This check doesn't work correctly when spinning up container
  # when: ssl_key.changed

- name:  Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "/etc/apache2/ssl/ssl.csr"
    privatekey_path: "/etc/apache2/ssl/ssl.key"
    common_name: "{{ HOSTNAME }}"
  # when: ssl_key.changed

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "/etc/apache2/ssl/ssl.crt"
    privatekey_path: "/etc/apache2/ssl/ssl.key"
    csr_path: "/etc/apache2/ssl/ssl.csr"
    provider: selfsigned
  # when: ssl_key.changed

- name: Configure apache proxy
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root

- name: restart apache
  service:
    name: apache2
    state: restarted
